### ISSUE TITLE
完善 ESLint 

### ISSUE THREAD

**Issue by bubkoo** [PaneJS/PaneJS#4]
熟悉之前的代码，并完善 ESLint @leungwensen, @tarobjtu

**Comment by leungwensen** [comment]
第一步： 通过eslint检查 https://github.com/PaneJS/PaneJS/pull/10

**Comment by leungwensen** [comment]
第二步：commit前lint https://github.com/PaneJS/PaneJS/pull/11

**Comment by bubkoo** [comment]
谈谈 JSCS：

> JSCS是一个代码风格检查器。这意味着它仅仅匹配代码格式的问题，不匹配潜在的bugs、errors。因此，跟其他工具相比缺少灵活性，但是如果你仅仅强制检查代码风格，JSCS也是一个好的工具。

看考这篇文章 [《javascript检验工具的比较》](http://developer.51cto.com/art/201506/481510.htm)

**Comment by leungwensen** [comment]
沿用ESlint
